#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Pyro4
Version  : 4.75
Release  : 5
URL      : https://files.pythonhosted.org/packages/a9/e6/07950f8efd3e6c781c46873c4f346fa6e56ca99330803511c956edd1096b/Pyro4-4.75.tar.gz
Source0  : https://files.pythonhosted.org/packages/a9/e6/07950f8efd3e6c781c46873c4f346fa6e56ca99330803511c956edd1096b/Pyro4-4.75.tar.gz
Summary  : distributed object middleware for Python (RPC)
Group    : Development/Tools
License  : MIT
Requires: Pyro4-bin = %{version}-%{release}
Requires: Pyro4-license = %{version}-%{release}
Requires: Pyro4-python = %{version}-%{release}
Requires: Pyro4-python3 = %{version}-%{release}
Requires: serpent
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
This is an example that more or less presents an online multiplayer game.
The game is a robot destruction derby.
It is played on a grid. There are some obstructing walls on the grid that
hurt when you collide into them. If you collide into another robot, the
other robot takes damage. All robots start with a certain amount of health.
If it reaches zero, the robot dies.  The last man standing wins!

%package bin
Summary: bin components for the Pyro4 package.
Group: Binaries
Requires: Pyro4-license = %{version}-%{release}

%description bin
bin components for the Pyro4 package.


%package license
Summary: license components for the Pyro4 package.
Group: Default

%description license
license components for the Pyro4 package.


%package python
Summary: python components for the Pyro4 package.
Group: Default
Requires: Pyro4-python3 = %{version}-%{release}
Provides: pyro4-python

%description python
python components for the Pyro4 package.


%package python3
Summary: python3 components for the Pyro4 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the Pyro4 package.


%prep
%setup -q -n Pyro4-4.75

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1547916116
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/Pyro4
cp LICENSE %{buildroot}/usr/share/package-licenses/Pyro4/LICENSE
cp docs/source/license.rst %{buildroot}/usr/share/package-licenses/Pyro4/docs_source_license.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pyro4-check-config
/usr/bin/pyro4-flameserver
/usr/bin/pyro4-httpgateway
/usr/bin/pyro4-ns
/usr/bin/pyro4-nsc
/usr/bin/pyro4-test-echoserver

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Pyro4/LICENSE
/usr/share/package-licenses/Pyro4/docs_source_license.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
